/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface KvSideDrawer {
    'open': () => void;
    'opened': boolean;
    'title': string;
  }
  interface KvSideDrawerAttributes extends StencilHTMLAttributes {
    'opened'?: boolean;
    'title'?: string;
  }

  interface KvStockPrice {
    'stockSymbol': string;
  }
  interface KvStockPriceAttributes extends StencilHTMLAttributes {
    'stockSymbol'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'KvSideDrawer': Components.KvSideDrawer;
    'KvStockPrice': Components.KvStockPrice;
  }

  interface StencilIntrinsicElements {
    'kv-side-drawer': Components.KvSideDrawerAttributes;
    'kv-stock-price': Components.KvStockPriceAttributes;
  }


  interface HTMLKvSideDrawerElement extends Components.KvSideDrawer, HTMLStencilElement {}
  var HTMLKvSideDrawerElement: {
    prototype: HTMLKvSideDrawerElement;
    new (): HTMLKvSideDrawerElement;
  };

  interface HTMLKvStockPriceElement extends Components.KvStockPrice, HTMLStencilElement {}
  var HTMLKvStockPriceElement: {
    prototype: HTMLKvStockPriceElement;
    new (): HTMLKvStockPriceElement;
  };

  interface HTMLElementTagNameMap {
    'kv-side-drawer': HTMLKvSideDrawerElement
    'kv-stock-price': HTMLKvStockPriceElement
  }

  interface ElementTagNameMap {
    'kv-side-drawer': HTMLKvSideDrawerElement;
    'kv-stock-price': HTMLKvStockPriceElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
