/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface KvSideDrawer {}
  interface KvSideDrawerAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'KvSideDrawer': Components.KvSideDrawer;
  }

  interface StencilIntrinsicElements {
    'kv-side-drawer': Components.KvSideDrawerAttributes;
  }


  interface HTMLKvSideDrawerElement extends Components.KvSideDrawer, HTMLStencilElement {}
  var HTMLKvSideDrawerElement: {
    prototype: HTMLKvSideDrawerElement;
    new (): HTMLKvSideDrawerElement;
  };

  interface HTMLElementTagNameMap {
    'kv-side-drawer': HTMLKvSideDrawerElement
  }

  interface ElementTagNameMap {
    'kv-side-drawer': HTMLKvSideDrawerElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
