/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface KvSideDrawer {
    'open': () => void;
    'opened': boolean;
    'title': string;
  }
  interface KvSideDrawerAttributes extends StencilHTMLAttributes {
    'opened'?: boolean;
    'title'?: string;
  }

  interface KvTooltip {
    'opened': boolean;
    'text': string;
  }
  interface KvTooltipAttributes extends StencilHTMLAttributes {
    'opened'?: boolean;
    'text'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'KvSideDrawer': Components.KvSideDrawer;
    'KvTooltip': Components.KvTooltip;
  }

  interface StencilIntrinsicElements {
    'kv-side-drawer': Components.KvSideDrawerAttributes;
    'kv-tooltip': Components.KvTooltipAttributes;
  }


  interface HTMLKvSideDrawerElement extends Components.KvSideDrawer, HTMLStencilElement {}
  var HTMLKvSideDrawerElement: {
    prototype: HTMLKvSideDrawerElement;
    new (): HTMLKvSideDrawerElement;
  };

  interface HTMLKvTooltipElement extends Components.KvTooltip, HTMLStencilElement {}
  var HTMLKvTooltipElement: {
    prototype: HTMLKvTooltipElement;
    new (): HTMLKvTooltipElement;
  };

  interface HTMLElementTagNameMap {
    'kv-side-drawer': HTMLKvSideDrawerElement
    'kv-tooltip': HTMLKvTooltipElement
  }

  interface ElementTagNameMap {
    'kv-side-drawer': HTMLKvSideDrawerElement;
    'kv-tooltip': HTMLKvTooltipElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
